# Per-class info, indexed to match the model's id2label order.
# (crop, condition, kind, severity, about, treatment[])
# kind: healthy | fungal | bacterial | viral | pest

_H = ("none","No signs of disease detected. Leaf colour and texture look normal.",
      ["Keep up regular watering at the soil line, not on leaves",
       "Maintain good airflow and balanced fertilisation",
       "Keep scouting weekly so problems are caught early"])

INFO = [
    ("Apple", "Apple Scab", "fungal", "moderate",
     "Caused by Venturia inaequalis. Olive-green to brown scabby lesions on leaves and fruit, worst in cool wet springs.",
     ["Rake and destroy fallen leaves in autumn", "Apply protectant fungicide (captan, mancozeb) from green-tip", "Prune for open canopy so leaves dry quickly", "Plant scab-resistant cultivars"]),
    ("Apple", "Black Rot", "fungal", "high",
     "Caused by Botryosphaeria obtusa. Purple-ringed leaf spots ('frogeye'), fruit rot and cankers on limbs.",
     ["Prune out cankers and dead wood", "Remove mummified fruit", "Apply captan or thiophanate-methyl during the growing season", "Sanitise pruning tools"]),
    ("Apple", "Cedar Apple Rust", "fungal", "moderate",
     "Gymnosporangium juniperi-virginianae. Bright yellow-orange spots on leaves; needs juniper/cedar as an alternate host.",
     ["Remove nearby junipers/cedars if practical", "Apply myclobutanil or mancozeb from pink bud", "Choose rust-resistant varieties"]),
    ("Apple", "Healthy", "healthy", *_H),
    ("Blueberry", "Healthy", "healthy", *_H),
    ("Cherry", "Powdery Mildew", "fungal", "moderate",
     "Podosphaera clandestina. White powdery growth on young leaves causing curling and distortion.",
     ["Prune to improve air circulation", "Apply sulfur or potassium bicarbonate at first sign", "Avoid excess nitrogen that drives soft growth"]),
    ("Cherry", "Healthy", "healthy", *_H),
    ("Corn", "Gray Leaf Spot (Cercospora)", "fungal", "high",
     "Cercospora zeae-maydis. Rectangular tan-gray lesions running parallel to leaf veins, favoured by humid weather and residue.",
     ["Rotate away from corn for 1–2 years", "Till under infected residue", "Plant tolerant hybrids", "Apply strobilurin/triazole fungicide at tasselling if pressure is high"]),
    ("Corn", "Common Rust", "fungal", "moderate",
     "Puccinia sorghi. Small cinnamon-brown pustules on both leaf surfaces.",
     ["Plant resistant hybrids", "Apply foliar fungicide if pustules appear early", "Scout from mid-vegetative stage"]),
    ("Corn", "Northern Leaf Blight", "fungal", "high",
     "Exserohilum turcicum. Long cigar-shaped gray-green lesions that merge and blight the leaf.",
     ["Use resistant hybrids", "Rotate crops and bury residue", "Apply fungicide at VT–R1 if lesions reach the ear leaf"]),
    ("Corn", "Healthy", "healthy", *_H),
    ("Grape", "Black Rot", "fungal", "high",
     "Guignardia bidwellii. Tan leaf spots with dark borders, and shriveled black mummified berries.",
     ["Remove mummies and infected canes", "Apply myclobutanil or mancozeb from bud break through bloom", "Open the canopy with shoot thinning"]),
    ("Grape", "Esca (Black Measles)", "fungal", "high",
     "A wood-decay complex. 'Tiger stripe' interveinal leaf scorch and speckled berries; can cause sudden vine collapse.",
     ["Prune in dry weather and seal large wounds", "Remove and burn severely affected vines", "No curative fungicide — focus on prevention"]),
    ("Grape", "Leaf Blight (Isariopsis)", "fungal", "moderate",
     "Pseudocercospora vitis. Irregular dark brown spots on older leaves, leading to early defoliation.",
     ["Remove infected leaves", "Apply copper or mancozeb fungicide", "Improve canopy ventilation"]),
    ("Grape", "Healthy", "healthy", *_H),
    ("Orange", "Citrus Greening (HLB)", "bacterial", "critical",
     "Candidatus Liberibacter, spread by the Asian citrus psyllid. Blotchy yellow mottling, lopsided bitter fruit; incurable.",
     ["Report to your local agriculture authority", "Remove and destroy infected trees", "Control psyllids with systemic insecticides", "Plant certified disease-free nursery stock"]),
    ("Peach", "Bacterial Spot", "bacterial", "moderate",
     "Xanthomonas arboricola pv. pruni. Small angular water-soaked spots that turn purple and drop out, leaving a shot-hole look.",
     ["Plant tolerant varieties", "Apply copper sprays early in the season", "Avoid overhead irrigation and excess nitrogen"]),
    ("Peach", "Healthy", "healthy", *_H),
    ("Bell Pepper", "Bacterial Spot", "bacterial", "moderate",
     "Xanthomonas campestris pv. vesicatoria. Dark, water-soaked leaf spots and raised scabby fruit lesions.",
     ["Use disease-free seed and transplants", "Apply copper + mancozeb sprays", "Rotate away from peppers/tomato for 2–3 years", "Avoid handling wet plants"]),
    ("Bell Pepper", "Healthy", "healthy", *_H),
    ("Potato", "Early Blight", "fungal", "moderate",
     "Alternaria solani. Dark concentric 'target' rings on older leaves, often on stressed plants.",
     ["Rotate crops (3 years)", "Apply chlorothalonil or mancozeb", "Keep plants well-fed and watered", "Remove volunteer potatoes"]),
    ("Potato", "Late Blight", "fungal", "critical",
     "Phytophthora infestans. Water-soaked greasy lesions with white mould underneath; can destroy a crop within days.",
     ["Act immediately — spreads fast in cool wet weather", "Remove and bag infected plants; destroy tubers", "Spray protectant/systemic fungicide (metalaxyl, cymoxanil)", "Use certified seed and resistant cultivars"]),
    ("Potato", "Healthy", "healthy", *_H),
    ("Raspberry", "Healthy", "healthy", *_H),
    ("Soybean", "Healthy", "healthy", *_H),
    ("Squash", "Powdery Mildew", "fungal", "moderate",
     "Podosphaera xanthii. White flour-like patches on leaf surfaces that reduce photosynthesis.",
     ["Apply sulfur, neem oil or potassium bicarbonate", "Space plants for airflow", "Choose resistant varieties", "Water at the base in the morning"]),
    ("Strawberry", "Leaf Scorch", "fungal", "moderate",
     "Diplocarpon earlianum. Many small purple spots that merge, giving leaves a scorched look.",
     ["Remove infected leaves after harvest", "Avoid overhead watering", "Renovate beds and rotate", "Use resistant varieties"]),
    ("Strawberry", "Healthy", "healthy", *_H),
    ("Tomato", "Bacterial Spot", "bacterial", "moderate",
     "Xanthomonas spp. Small dark greasy spots on leaves and rough scabs on fruit.",
     ["Use clean seed/transplants", "Copper-based sprays", "Rotate and avoid working wet plants", "Remove crop debris"]),
    ("Tomato", "Early Blight", "fungal", "moderate",
     "Alternaria solani. Brown spots with concentric rings, starting on lower leaves.",
     ["Remove lower infected leaves", "Mulch to stop soil splash", "Apply chlorothalonil or copper fungicide", "Rotate crops"]),
    ("Tomato", "Late Blight", "fungal", "critical",
     "Phytophthora infestans. Large olive-brown blotches with pale halos, white fuzz in humid conditions; rapidly fatal.",
     ["Remove and destroy infected plants immediately", "Apply fungicide (mancozeb, chlorothalonil) preventively", "Avoid overhead irrigation", "Do not compost infected material"]),
    ("Tomato", "Leaf Mold", "fungal", "moderate",
     "Passalora fulva. Pale yellow patches on top of leaves with olive velvety mould below; thrives in high humidity.",
     ["Lower humidity and ventilate greenhouses", "Stake and prune for airflow", "Apply copper or chlorothalonil", "Use resistant cultivars"]),
    ("Tomato", "Septoria Leaf Spot", "fungal", "moderate",
     "Septoria lycopersici. Many small circular spots with dark borders and gray centres.",
     ["Remove affected lower leaves", "Mulch and water at the base", "Apply chlorothalonil or copper", "Rotate for 2–3 years"]),
    ("Tomato", "Spider Mites", "pest", "moderate",
     "Tetranychus urticae. Tiny stippling on leaves, bronzing and fine webbing, worst in hot dry weather.",
     ["Spray plants with a strong stream of water", "Apply insecticidal soap, neem or horticultural oil", "Release predatory mites", "Keep plants watered; avoid dust and drought stress"]),
    ("Tomato", "Target Spot", "fungal", "moderate",
     "Corynespora cassiicola. Brown lesions with concentric rings and yellow halos on leaves and fruit.",
     ["Improve air circulation and prune", "Apply chlorothalonil or azoxystrobin", "Remove crop debris"]),
    ("Tomato", "Yellow Leaf Curl Virus", "viral", "high",
     "TYLCV, spread by whiteflies. Upward-curling, yellowed leaves, stunted growth and poor fruit set.",
     ["Control whiteflies (sticky traps, reflective mulch, insecticides)", "Remove and destroy infected plants", "Use virus-resistant varieties", "Screen seedlings/greenhouses with insect netting"]),
    ("Tomato", "Mosaic Virus", "viral", "high",
     "ToMV. Mottled light and dark green leaf patterns, distortion and reduced yield; spreads by contact.",
     ["Remove and destroy infected plants", "Wash hands and disinfect tools", "Do not smoke near plants (tobacco carries virus)", "Use resistant varieties and clean seed"]),
    ("Tomato", "Healthy", "healthy", *_H),
]
